#!/bin/bash

dir="`dirname $0`"

# config
URL=$(jq -r '.URL' "$dir"/checklist.json)
BRANCH_ARG=$(jq -r '.branch? // empty | "--branch " + .' "$dir"/checklist.json)

# Prepare repo:
r=`mktemp -d -t repo.XXXXXXXXXX`
[ -z "$r" ] && exit 2

git clone --depth=1 "$URL" $BRANCH_ARG "$r"

# Generate file if it doesn't exist yet:
f=`date +%Y%m%d.md`
d=`date +%Y-%m-%d`
[ -e "$r"/"$f" ] || sed -e 's/%DATE%/'"$d"'/' "$dir"/checklist.template >"$r"/"$f"

# Add, commit, push:
git -C "$r"/ add "$f"
git -C "$r"/ commit -m new "$f"
git -C "$r"/ push

# Clean up:
rm -rfv "$r"
