#!/bin/bash

dir="`dirname $0`"

# Read config:
pick() { jq -r "$1" <"$dir"/checklist.json; }
URL=`pick '.["URL"]'`
branch=`pick '.["branch"]'`

# Prepare repo:
r=`mktemp -d -t repo.XXXXXXXXXX`
[ -z "$r" ] && exit 2
git clone --depth=1 "$URL" --branch "$branch" "$r"

# Generate file if it doesn't exist yet:
f=`date +%Y%m%d.md`
d=`date +%Y-%m-%d`
[ -e "$r"/"$f" ] || sed -e 's/%DATE%/'"$d"'/' "$dir"/checklist.template >"$r"/"$f"

# Add, commit, push:
git -C "$r"/ add "$f"
git -C "$r"/ commit -m new "$f"
git -C "$r"/ push

# Clean up:
rm -rfv "$r"
